---
- name: Apply common config to all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Initialize Kubernetes master
  hosts: master
  become: true
  roles:
    - master

- name: Join worker to the cluster
  hosts: worker
  become: true
  roles:
    - worker
